### ISSUE TITLE
Problem in 2D Band Structure Plotting

### ISSUE THREAD

**Issue by shahid-sattar** [hungpham2017/mcu#4]
After a recent ubuntu update, it seems that there is now a problem in plotting 2D Band structure with mcu. 
Kindly see attached screenshot and suggest how it can be resolved. 
![Screenshot from 2020-04-28 12-32-28](https://user-images.githubusercontent.com/61748682/80477623-8d568980-894c-11ea-8d14-1bf84263c09d.png)

**Comment by hungpham2017** [comment]
there is little change in Matplotlib that has not been updated in MCU the master branch yet.
This is fixed in the latest commit in the dev branch. I am working on the first official release of mcu which will be available to install via pip as well as conda install.
In the meantime, you can pull the new version:

`git clone -b dev https://github.com/hungpham2017/mcu.git`

Let me know if it solves your problem

**Comment by shahid-sattar** [comment]
Thanks a lot for quick response. The problem is now solved. 
Best,

**Comment by hungpham2017** [comment]
great!
